### ISSUE TITLE
Confusion on how to change language

### ISSUE THREAD

**Issue by HotelLima521** [csoc-de/Shifts#10]
Hey, I recently installed this on my nextcloud instance and can't seem to figure out how to change the language to English, am I completely oblivious as to how to do this, or is there just no support for English at the moment?

Thanks for the awesome app however!!

**Comment by fkirchesch** [comment]
Hey,
unfortunately there is no support for English at this moment as i haven't had the time to implement the translations.
Im sorry for the inconvenience, i will try to implement it as soon as possible.

 Thanks for the compliment :D.

Best regards

Fabian

**Comment by fasalsh** [comment]
Upvote on this feature

**Comment by fkirchesch** [comment]
Hey @HotelLima521 and @fasalsh,
as you might have noticed, i have just released a new version which includes the translations to the English Version.
If you find any translation errors, please contact me or open a new issue.

Best regards

Fabian
