### ISSUE TITLE
Missing something importend in configuration?

### ISSUE THREAD

**Issue by BernhardFahr** [csoc-de/Shifts#12]
First of all, I want to say that this app is a gift!
Unfortunately, I guess I'm too stupid to configure it.

![grafik](https://user-images.githubusercontent.com/66071866/143866814-1a83eec6-e384-4e2a-9ed3-4abf5c10191b.png)

I can't see "Shift types" and "Shift data" after installation and configuration. Also the two buttons "Assign new shift" and "Synchronize calendar" are missing.
I have made the assignment in the config....

It may well not be a bug in the app.... But, since there is no forum, I'll try an issue.

**Comment by fkirchesch** [comment]
Hey @BernhardFahr,
for the app to function as intented, i have implemented two simple nextcloud-user group differentiation. There is the shiftworker/analyst group which you can use to allow users to be assigned to shifts and there is a group for the administrative Users in the app itself, these users can organize shifts, add new shifttypes and so on and so forth.

I think what is happening here is that the user you are using to open the app doesnt belong to the admin-group and cannot see these buttons only intended for the admins.

Unfortunatly, these groups have to be added manualy to the nextcloud-environment and the names of the groups have to then be set in the app settings found under "Settings -> Shifts" when logged in as a nextcloud-admin.

I hope this helped, feel free to update this issue when it didnt.

Furthermore may i ask you a question regarding Documentation, i have listed these settings in the docs/Readme.md File but im afraid that it wont be seen by many. Where do you think i should document these required settings?

Best Regards

Fabian

**Comment by BernhardFahr** [comment]
Hello Fabian,
yes, I found the admin documentation and created the corresponding calendars, groups, etc. (see picture).
![grafik](https://user-images.githubusercontent.com/66071866/144037941-fe1ec011-dbfe-4b7b-9a7b-8e6912533a63.png)

**Comment by fkirchesch** [comment]
Hey,
Is the user you are using to open the app assigned to the "ShiftsAdmin" group ?
and
Does an error appear on the top left corner when open the app?

Best regards

Fabian

**Comment by BernhardFahr** [comment]
Hello Fabian,

yes, definitly the user is in the admin group. And no: no error while opening.
This is how it looks like:
![grafik](https://user-images.githubusercontent.com/66071866/144039239-5063c0ba-9b9c-4d37-82d4-fb1a7d1a2694.png)

**Comment by fkirchesch** [comment]
Mhhh, I cant think of another reason why there wouldnt be the admin only buttons/menus but everything else is rendering without errors

**Comment by BernhardFahr** [comment]
Hello Fabian,
i will check it again.

**Comment by BernhardFahr** [comment]
i have made: occ group:list
Result: Shiftadmin (name of the group).
My user is in that group.
But....!
but in the settings for the app I had entered shift**s**admin :-(
small error, big effect. Now it works like magic!
Big apologies for the effort

**Comment by fkirchesch** [comment]
Ah ok, no worries :D

unfortunately i have not yet found a better solution for setting the group other than with a string. I think i have to replace the string input with a select menu with all nextcloud shifts.

Best regards

Fabian
