### ISSUE TITLE
it doesn´t work

### ISSUE THREAD

**Issue by Harveynumber9** [csoc-de/Shifts#13]
Moin,
irgendwas scheine ich total falsch zu machen. 
![grafik](https://user-images.githubusercontent.com/95305461/144094801-821e4798-266d-4f2d-87f6-f6a41eb5e7e1.png)
Der Schichtplan wird angezeigt jedoch ohne die Möglichkeit Schichten einzuplanen oder zu ändern.

Gruß
Harvey

**Comment by fkirchesch** [comment]
Hey @Harveynumber9,

ich denke hierbei handelt es sich, ähnlich wie in Issue #12, um eine fehlende Userzuweisung in die Gruppe der Schichtadmins. Könntest du mal nachschauen, ob der User, mit dem du die App öffnest in der Gruppe ist, welche du in den Schichtplan Einstellungen als Schichtadmin-Gruppe du definiert hast.

Gruß

Fabian

**Comment by Harveynumber9** [comment]
Moin Fabian,
das hat geholfen. Den Issue 12 hatte ich nicht gefunden aber das war genau das Problem. Ich hatte bei Shiftsadmin das s vergessen. 
Super Danke.

**Comment by fkirchesch** [comment]
Ok, dann kann ich das Issue ja schließen.
