### ISSUE TITLE
Kann keine Schicht anlegen

### ISSUE THREAD

**Issue by Harveynumber9** [csoc-de/Shifts#14]
Moin,
hab mich leider zu früh gefreut.
Ich kann jetzt den Dialog "neue Schicht" sehen jedoch schaffe ich es nicht irgendeine neue Schicht einzutragen. Denke das hat mit dem Kalender zu tun. Ich bekomme die Wochenansicht nur für Daten der Vergangenheit der Kalender bleibt in der letzten Nov. Woche stehen. Wenn ich auf neue Schicht anlegen gehe kann ich die Schicht auswählen und den Mitarbeiter und auch Tage auswählen. Wenn ich dann auf speichern gehe wird der Mitarbeiter gelöscht und dann hab ich in der Auswahl nur noch ? stehen.
Der Kalender ist vorhanden mit richtiger Bezeichnung der Schichtadmin hat Bearbeitungsrechte die Mitarbeiter sind in der Gruppe der Analysten und haben das Skillevel Level1. Ich hab keine Idee mehr was ich noch testen kann.
![grafik](https://user-images.githubusercontent.com/95305461/144232018-90970d50-2f59-4e02-9f80-51c54076c449.png)
![grafik](https://user-images.githubusercontent.com/95305461/144232083-7f1c6650-c5cf-4dc4-86b3-2970c6655f15.png)
![grafik](https://user-images.githubusercontent.com/95305461/144232177-69651093-b61e-4c9b-ba46-eea7f87c8949.png)

Gruß
Harvey

**Comment by Harveynumber9** [comment]
Ich habe mal die Fehlermeldung aus dem LOG angefügt.:
<html><body>


  | Exception: Argument  1 passed to OCA\Shifts\Controller\ShiftController::create() must be of  the type string, null given, called in  /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line  217/var/www/nextcloud/lib/private/AppFramework/App.php - line 156: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 1006: OC\Route\Router->match()/var/www/nextcloud/index.php - line 36: OC::handleRequest()Verursacht durch TypeError: Argument  1 passed to OCA\Shifts\Controller\ShiftController::create() must be of  the type string, null given, called in  /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line  217/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217: OCA\Shifts\Controller\ShiftController->create()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126: OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 156: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 1006: OC\Route\Router->match()/var/www/nextcloud/index.php - line 36: OC::handleRequest()
-- | --



</body>
</html>

Die hilft mir leider auch nicht weiter.

Gruß
Harvey

**Comment by fkirchesch** [comment]
Hey @Harveynumber9,
der erste Bug mit den Fragen wird in der neuen Version behoben sein, hier hat sich ein kleiner Fehler eingeschlichen wobei eine falsche Liste überarbeitet wird, sodass die benötigten Felder für die Darstellung unter anderen Namen zu finden waren.
Deshalb kommt auch der im Logausschnitt.

Den Fehler des hängen gebliebenen Kalenders kann ich momentan leider noch nicht reproduzieren oder nachvollziehen, ich sitze aber gerade dran.

Sorry für die ganzen Bugs :D


Gruß

Fabian

**Comment by Harveynumber9** [comment]
Hallo Fabian,
ist ein tolles Projekt. Bin gespannt wie es weitergeht.
Gruß
Harvey

**Comment by fkirchesch** [comment]
Hey @Harveynumber9,
ich habe gerade eine neue Version released in der die hier genannten Issues behoben sein sollten. Ich gehe davon aus der der hängen gebliebene Kalender mit dem anderen Fehler zusammenhängt. Da dieser behoben ist, sollten nun beide nicht mehr vorkommen. 

Falls doch, einfach melden :D.

Gruß 
Fabian
