### ISSUE TITLE
Komplette Wochen verschwinden in der Schichtplan ansicht

### ISSUE THREAD

**Issue by Damontir** [csoc-de/Shifts#15]
Moin,

erstmal danke für diese App, ich hab für einen Auftraggeber genau nach sowas schon länger gesucht :)

Ich hab die App heute mal ein wenig getestet und bin auch nen Bug gestoßen der komplette Wochen aus dem Kalender verschwinden lässt. Ich hab auch noch keine Lösung dafür gefunden..

Wenn du einen Schichttyp anlegst, der Wöchentlich geht (3x in meinem Bspl.) und diesen dann in der Schichtplan Übersicht versuchst diese Schicht via Drag and Drop auf einen Mitarbeiterslot z.B. Mittwochs hinziehst, hängt die Cloud für nen bisschen und nachdem sich die Seite neu aufgebaut hat, erscheinen diese Wochen, in denen die Schicht geschoben wurde nicht mehr auf.

Selbst nachdem die App neu installiert worden ist & ein anderer Kalender genutzt wurde, tauchen diese Wochen nicht mehr auf.

Hab auch in den Daten auf dem Server und in der MariaDB nachgesehen und keine Einträge gefunden, die dieses eventuell blockieren.

Danke!
LG aus Bremen

**Comment by fkirchesch** [comment]
Hey @Damontir 
sorry das ich jetzt erst antworten kann, ich hatte leider ein wenig Stress. 
So wie ich das interpretiere, hast du einen wöchentlichen Schichttypen angelegt und möchtest diesen nun auf einen spezifischen Tag, in deinem Beispiel Mittwoch, und Mitarbeiter zuweisen. 

Das ist so leider nicht möglich und sollte von Programm unterdrückt werden. Ich werde dies ebenfalls in einer neuen Version unterbringen.

Mit dem Feld der wöchentlichen Schichten sind Schichten gemeint, die über die gesamte Woche gelten.

Warum jedoch nun diese Wochen komplett verschwinden erklärt sich mir noch nicht, könntest du vielleicht versuchen das Problem zu reproduzieren und mir mögliche Fehler aus der Browser-Konsole zukommen lasse?

Ich hoffe ich konnte dir trotz Verspätung helfen.

Gruß 

Fabian

**Comment by fkirchesch** [comment]
Hey @Damontir,
ich habe gerade eine neue Version veröffentlicht in der das genannte Unterdrückung des Verschieben von wöchentlichen Schichten enthalten ist. Sollte der Bug dennoch vorkommen kannst du dich gerne melden.

Gruß
Fabian
