### ISSUE TITLE
"Kalendar konnte nicht aktualisiert werden"

### ISSUE THREAD

**Issue by eiks25** [csoc-de/Shifts#22]
Hallo,

folgende Fehlermeldung wird beim Versuch Shifts mit dem Kalender zu syncen ausgegeben:

"Kalendar konnte nicht aktualisiert werden"

Version: 1.8.3
Nextcloud 22.2.3

Im nextcloud.log findet sich folgender Fehler:
```
0,"time":"2022-01-06T10:18:44+00:00","remoteAddr":"192.168.1.111","user":"Schichtadmin","app":"files_sharing","method":"GET","url":"/nextcloud/index.php/apps/shifts/shiftsCalendarChange","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0"}
{"reqId":"BmdRcBloNKTOA8DBLRIH","level":0,"time":"2022-01-06T10:18:44+00:00","remoteAddr":"192.168.1.111","user":"Schichtadmin","app":"files_sharing","method":"PROPFIND","url":"/nextcloud/remote.php/dav/calendars/Schichtadmin/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"22.2.3.0"}
```
In der Übersetzung ist auch ein kleiner Typo "Kalend**a**r" anstatt "Kalender".

Ansonsten sind alle weiteren Funktionen i.O.

Die App hatte mit einer älteren Version / Installation von Nextcloud inkl. Kalendersync funktioniert, auf einer Neuinstallation mit 22.2.3 kommt obige Fehlermeldung.

Danke für die App & Grüße

**Comment by fkirchesch** [comment]
Hallo @eiks25,
sorry für die lange Wartezeit, die Bachelorarbeit hat doch mehr Zeit gefressen als gedacht.

Zunächst danke für den Typo, wäre ich nie drauf gekommen oder gesehen :D.
Weiterhin konnte ich die App noch nicht mit Nextcloud 22.2.3 testen und es könnte sein das diese Version mit dem Fehler zusammenhängt.
Der Fehler hat leider nichts mit der Fehlermeldung in der App zu tun und ist laut einem Nextcloud-Dev normal: https://github.com/nextcloud/server/issues/23046#issuecomment-708420457

Ich werde mich sobald ich Zeit habe, wahrscheinlich erst nächste Woche, mit einigen Issues befassen und hoffe auf eine schnelle neue Version die diesen Fehler löst.

Mit freundlichen Grüßen

Fabian

**Comment by Manuelibt** [comment]
Hi, 

ich habe hier das gleiche Problem, wie oben beschrieben. 

Hast du mittlerweile etwas mehr Zeit um dich um diese App zu kümmern? 
Die Firma (kleiner sozialer Trägerverein) wäre sehr daran interessiert, diese App produktiv zu nutzen. Allerdings sollten die Kinderkrankheiten aus dem Weg geräumt werden, bevor ich sie vorstelle ;). 

Können wir irgendwie direkt in Kontakt treten? 

Herzliche Grüße 
Manuel

**Comment by csoc-kevink** [comment]
Hi,

tritt der Fehler mit Version v1.9.1 immer noch auf?

Viele Grüße
Kevin
