### ISSUE TITLE
Non usable App-Screen with no function?

### ISSUE THREAD

**Issue by mave-git** [csoc-de/Shifts#27]
![shiftplan](https://user-images.githubusercontent.com/65040899/155007311-90b81c16-339d-4b7d-9e48-e216baa79f9c.jpg)
Hello,
after installation and getting rid if error-message "Could not fetch data / Daten konnten nicht geladen werden" by creating groups
Analyst
Level 1
Shiftsadmin

and calendar 
ShiftsCalendar

and checking the Shifts-Settings, i only get a non usable App-Screen with no function ... Anything forgotten?

Uuups, und das Ganze hätte ich ja auch gleich deutsch verfassen können ;-)

**Comment by fkirchesch** [comment]
Hallo @mave-git,
ich antworte jetzt einfach mal auf deutsch :D

Da du von keiner Fehlermeldung in Verbindung mit dem Problem berichtest, gehe ich davon aus das der User, mit dem du gerade auf die App zugreift nicht Mitglied in der Shifts-Admin Gruppe ist. Das ist ebenfalls eine neue Gruppe von Nutzern für die Schichtenapp, bei den alle Mitglieder die App administrieren können, sprich Schichttypen hinzufügen oder Schichten anlegen. Diese Gruppe musst du leider selber anlegen und dann den exakten Namen in den Schichtapp-einstellungen hinterlegen.

Mit freundlichen Grüßen

Fabian Kirchesch

**Comment by Thelendris** [comment]
Hallo @fkirchesch,
da ich den gleichen Fehler in meiner NC habe wie Mave, eröffne ich dafür mal kein neues Issue. Deiner kleinen Anleitung hier folgend, habe ich eine Shiftadmin-Gruppe erstellt (gleicher Name in den Shift-Einstellungen), einen NC-Admin dieser Gruppe hinzugefügt und leider kommt trotzdem noch die Meldung "Daten konnten nicht geladen werden". Die Situation in der App selbst stellt sich so dar, wie auf dem Screenshot von Mave zu sehen.
Gibt es noch weitere Einstellungen/Anpassungen, die irgendwo vorgenommen werden müssen? Wenn ja, habe ich diese leider übersehen.

Beste Grüße und danke für die Arbeit mit diesem Projekt!

**Comment by mave-git** [comment]
![shiftplan_288222 pg](https://user-images.githubusercontent.com/65040899/156056588-0ddc3855-120d-4806-a79c-ba703826512a.jpg)
Hallo @fkirchesch,
recht schönen Dank für die Rückmeldung. Nach (manuellem) Anlegen nötiger Gruppen komme ich immerhin etwas weiter. Es mag auch am Verständnis liegen, "durchzusteigen", welche User zu welchen Gruppen von Shiftplan zugeordnet werden müssen (da ist für _mich_ die Installationsbeschreibung nicht klar genug). Indes bleibt, dass Daten nicht geladen werden können, beim Kalender erfolgt Sync-Fehler. Log kann ich nicht liefern, das es eine gehoste NC-Instanz ist (oder ist die verfügbar?). Auf meinen Konetxt bezogen, scheint das eben aktuell nicht test- und nutzbar zu sein. Allemal. Viel Erfolg!
