### ISSUE TITLE
Cannot go beyond last week in April / April 30 / current week / month

### ISSUE THREAD

**Issue by LeaKaftan** [csoc-de/Shifts#31]
Hi csoc-de,

Thank you for this wonderfull app! I have encountered an issue when I want to move beyond the current week or current month and see the shifts I added for the upcoming weeks. So I have a calendar in the shift app for April 25 - May 01, but if I click on the right arrow to move forward, only the name of the month changes, but not the date nor the shifts. Moving back in time works fine. Let me know if you need more information to fix this issue.

Best,
Lea

**Comment by csoc-kevink** [comment]
Hi Lea,

does this error still appear in the new version?

**Comment by LeaKaftan** [comment]
Hihi, sorry for the late reply. I do not know, to be honest, and I am in the mids of moving institutionally so I won't have much time trying it out in the upcoming weeks, since we are also currently not using the shifts. Sorry. Thanks for reaching out and all the best! Lea

**Comment by csoc-kevink** [comment]
Ok, no problem. I will close the issue for now. If you experience any other issues, you can reach out to us
