### ISSUE TITLE
Will there be a version für Nextcloud 24?

### ISSUE THREAD

**Issue by oswaldo-be** [csoc-de/Shifts#32]
I just want to know, because then I would have to find an alternative.

Thanks

**Comment by tuxnetDE** [comment]
Too bad that this great extension does not work with nextcloud 24

**Comment by benhartwich** [comment]
Same here - app doesn´t work with the current version. Chrome error log:
```
Failed to load resource: the server responded with a status of 500 ()
database.js:184 Error: Request failed with status code 500
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:54:1)
```

nextcloud error log:
`{"reqId":"kd0EHEnHyJOehTgeD4vC","level":3,"time":"2022-08-23T12:33:53+02:00","remoteAddr":"91.114.81.36","user":"","app":"index","method":"GET","url":"/apps/shifts/getAllAnalysts","message":"Call to a member function getUsers() on null in file '/var/www/cloud/htdocs/nextcloud/apps/shifts/lib/Controller/ShiftController.php' line 154","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36","version":"24.0.4.1","exception":{"Exception":"Exception","Message":"Call to a member function getUsers() on null in file '/var/www/cloud/htdocs/nextcloud/apps/shifts/lib/Controller/ShiftController.php' line 154","Code":0,"Trace":[{"file":"/var/www/cloud/htdocs/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/cloud/htdocs/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/cloud/htdocs/nextcloud/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/cloud/htdocs/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/cloud/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"Error","Message":"Call to a member function getUsers() on null","Code":0,"Trace":[{"file":"/var/www/cloud/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getAllAnalysts","class":"OCA\\Shifts\\Controller\\ShiftController","type":"->"},{"file":"/var/www/cloud/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/cloud/htdocs/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/cloud/htdocs/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/cloud/htdocs/nextcloud/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/cloud/htdocs/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/cloud/htdocs/nextcloud/apps/shifts/lib/Controller/ShiftController.php","Line":154},"CustomMessage":"--"},"id":"6304ad3a0716a"}`

**Comment by KaiBuskirk** [comment]
Hello... No Luck with an update?
is there a team to help this along?
cheers, kai

**Comment by krauthaus** [comment]
It looks dead jim. It is sad since this would be a absolute killer-plugin; I would pay for stuff like that! I hope someone with code-skills is in grateful mood to help us out!

**Comment by sq5gvm** [comment]
> Same here - app doesn´t work with the current nextcloud 24 version. Chrome error log:

I'm trying to get it working in version 24 too. 
The problem you see is caused from incorrect plugin config. See Settings -> Administration -> Timeshift and make sure that you've entered correct group names in appropriate fields.

**Comment by Chiller2019** [comment]
Jeahr, now to Nextloud25, I wish this plugin was updated .... very very nice plugin .... sad for the community

**Comment by michajonas** [comment]
Hey all,
sorry for the delay. We are currently working on an updated version for Nextcloud25.

**Comment by Router1982** [comment]
Pls make a Update for NC 24 / 25 and NextCloudPI
The Tool is very cool. But not Working by me.

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by csoc-technik** [comment]
Hey all,
due to various internal projects, the release is unfortunately delayed. We thank you for your patience. There will be a working version for Nextcloud 25, which will continue to be maintained.

**Comment by codingMel** [comment]
it's released! Thank you!
but could you also [upload](https://nextcloudappstore.readthedocs.io/en/latest/developer.html) it to the [apps-store](https://apps.nextcloud.com/apps/shifts) that we can [install](https://github.com/csoc-de/Shifts/blob/master/docs/README.md)/try it out?

**Comment by csoc-kevink** [comment]
We uploaded the new version v1.9.1 to the appstore. This version is compatible with nextcloud version 25 and 26.
The old releases were deleted from the appstore since we had to reregister our app.

If you find bugs or have any feature request feel free to make a pull request or a new issue :)
