### ISSUE TITLE
missing js folder

### ISSUE THREAD

**Issue by sonaxpro** [csoc-de/Shifts#38]
I'm continuing to further investigate this plugin and what I finded:

in templates/main.php is this code 
`script('shifts','shifts-main');`
It add in HTML this:
`<script nonce="...=" defer src="/custom_apps/shifts/js/shifts-main.js?v=47a44f65-0"></script>`

But in this repo is not folder **js** and too **js/shifts-main.js** 
therefore, an error 404 is obtained

I tried it on versions 25 and 26

**Comment by sonaxpro** [comment]
in _templates/settings.php_ is this code too
`script('shifts','shifts-settings');`

and js/shifts-settings.js = 404 too

**Comment by csoc-kevink** [comment]
The js folder should be created when you build the app.
We use this app internally and it is working so far (with some minor bugs).
Is the app loading or what error do you exactly encounter?
