### ISSUE TITLE
Daten und Einstellungen können nicht geladen werden

### ISSUE THREAD

**Issue by Router1982** [csoc-de/Shifts#44]
Gibt es Probleme wenn Nextcloud als Docker Container läuft?
Bzw eine Andere Einrichtungsanleitung
![Screenshot (20)](https://github.com/csoc-de/Shifts/assets/118884249/2dd6dd02-0e1b-407d-a0a3-69139f16f409)
![Screenshot (19)](https://github.com/csoc-de/Shifts/assets/118884249/0220eb2d-1e24-4c62-83a0-6e73a5af78d4)

**Comment by csoc-kevink** [comment]
Eigentlich sollte es keine Unterschiede geben.
In der Browser-Konsole müssten evtl. etwas mehr Informationen zu dem Fehler stehen (F12 > Konsole). Kannst du den Inhalt davon mal posten (wenn keine sensiblen Daten zu sehen sind).
Die Server-Logs zu dem Fehler wären am hilfreichsten, weil dort ein Stack-Trace sein müsste.

**Comment by Router1982** [comment]
Hi der Fehler scheint folgender zu seine leider hab ich keinen ansatz
Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://xxxxxxxxxxx.duckdns.org/apps/shifts/settings/ blockiert ("connect-src"). shifts

**Comment by csoc-kevink** [comment]
Hi,
da scheint etwas mit der Content-Security-Policy nicht zu stimmen (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src).
Läuft da vllt irgendwo ein Proxy zwischen dem Browser und der Nextcloud-Instanz?

**Comment by Router1982** [comment]
nein nix dazwischen. hab die installation jetzt mal manuel versucht kann es am verwendeten Docker Linux /alpine linux liegen , wie es aussieht existiert der User und die Gruppe www-data nicht

**Comment by csoc-kevink** [comment]
Wurde die App über den App-Store installiert oder versucht manuell zu bauen (npm und node)?

**Comment by Router1982** [comment]
Über den store bekomme ich die fehler im bild. Und Manuell müsste ich denke ich die config anpassen (user und verzeichnisse) unter Debian und NC scheint es soweit zu laufen

**Comment by csoc-kevink** [comment]
Vllt lag es dann wirklich am Docker-Image, wie du oben gesagt hast.
Aber du hast eine funktionierende Instanz hinbekommen?

**Comment by Router1982** [comment]
Wäre es möglich die Einrichtungs - Anleitung zu überarbeiten ich denke ich hab da nen Fehler und komme nicht weiter

**Comment by csoc-kevink** [comment]
Die Dokumentation wurde vor einiger Zeit von privatemaker aufgefrischt.
Dass die Admin-Einstellungen nicht laden, hab ich bisher noch nicht gesehen/nachstellen können.
Falls das Problem noch besteht, kannst du zeigen, was in der Browser-Konsole steht (Ohne sensible Informationen)?

**Comment by Kyrinja** [comment]
Auch bei mir laden die Einstellungen nicht und kann daher nichts konfigurieren. 

den Fehler habe ich im Log:
Call to a member function getUsers() on null in file '/var/www/nextcloud/apps/shifts/lib/Controller/ShiftController.php' line 189

**Comment by csoc-kevink** [comment]
In Zeile 189 der ShiftController.php wird versucht alle Benutzer der Analysten-Gruppe abzufragen:
```php
$groupName = $this->settings->getShiftWorkerGroup();
$group = $this->groupManager->get($groupName);
$users = [];
$result = $group->getUsers();
```
Bitte stellt sicher, dass eine allgemeine Gruppe für alle, die die Shift-App benutzen sollen existiert und für jedes Level eine Gruppe. Die Gruppen-Namen müssen exakt übereinstimmen, da die App/Nextcloud sonst die Gruppe nicht finden können.
In Issue #65 hat jemand beobachtet, dass nur der initiale Gruppenname von der Nextcloud übernommen wird und spätere Änderungen am Namen nicht zwangsläufig zur Änderung der Gruppen-ID führen.

**Comment by Kyrinja** [comment]
Vielen Dank, das haben wir umgesetzt kann aber weiterhin nichts Angezeigt werden. In der Konsole wird folgendes angezeigt: AxiosError: Request failed with status code 404
    at https://domain/apps/shifts/js/shifts-settings.js?v=3c3e77ce-19:2:3941544
    at XMLHttpRequest.d (https://domain/apps/shifts/js/shifts-settings.js?v=3c3e77ce-19:2:3941692)

**Comment by csoc-kevink** [comment]
Mit welcher Anfrage ist dieser Fehler denn verbunden? Da die Fehlermeldung auf die minifizeirte shift-settings.js Datei verweist, dann ich leider nicht so einfach nachvollziehen, wo der Fehler entstanden ist.
Gibt es in der Konsole oder im Netzwerk-Tab vom Browser noch hinweise, welche Anfrage fehlgeschlagen ist?
