### ISSUE TITLE
Unable to configure Shiftplan due to 405 request error

### ISSUE THREAD

**Issue by privatemaker** [csoc-de/Shifts#52]
I installed Shiftplan on a NextCloud at v25.0.4 and I'm unable to set it up at all. 
Upon accessing the settings at:

```
https://mynext.cloud/settings/admin/shifts
```

Upon clicking on the `Save` button which makes a PUT request to `/apps/shifts/settings` the request errors out with `405` which shows following response:

```
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
```

Is this due to which of the following:

- Some NC server configuration on my side?
- An error just related to NC v25
- A legitimate bug with Shiftplan worth investigating further? 

Maybe relates to issues discussed in [this comment](https://github.com/csoc-de/Shifts/issues/42#issuecomment-1747090429) in #42 ?

After a fresh install on a NC v28, things work fine, so perhaps this issue only pertains to NC v25?

**Comment by csoc-kevink** [comment]
Hi,

a 405 error comes most likely from nextcloud itself since the shifts app only checks if someone is in the shiftadmin group and nothing else. the rest should be handled by nextcloud.

If it works in a newer version it could really be a problem with nextcloud.
