### ISSUE TITLE
Closed-Source library involved - Please adapt description and License Terms

### ISSUE THREAD

**Issue by florom** [csoc-de/Shifts#6]
Hi,

you state that you include 
"
Integration of existing Open-Source Software! Using the great Gantt-schedule-timeline-calendar and many more libraries
"
This is wrong. For details read: 

https://help.nextcloud.com/t/app-schichtplan-requires-license/126144

In the documentation here  and on 
https://apps.nextcloud.com/apps/shifts

Please adapt your descriptions accordingly.

**Comment by blackcrack** [comment]
pity , it's a good idea to have a nice app for managing shifts and plans.. it should be exist a new repo with a real "Open Source" Licence to have a pretty good possible for check out the actual plan of working .. and also for Security personal for earch singe Security Employee and or Employee in IT or others..  why should not use this idea to make a real open source solution for NC... like NCDownloader.. as example ..

best regards
Blacky
Blackysgate.de

**Comment by fkirchesch** [comment]
Hello again,
im pleased to announce that i have updated the app with a new method of display the shifts. In the new Release 1.8.0 there is no more association to the gstc Calendar. Instead i implemented it using a simple html table with the included drag and drap api 

best regards 
Fabian Kirchesch
csoc-de
