### ISSUE TITLE
Tagesübergreifende Schichten sind einen Tag verschoben

### ISSUE THREAD

**Issue by ikkez** [csoc-de/Shifts#62]
Wenn ich eine Schicht von 22:00 bis 01:30 Uhr anlege, dann werden diese beim synchronisieren in den Kalender mit einen Tag Versatz zu früh angelegt.

<img width="519" alt="Bildschirmfoto 2024-01-09 um 15 51 34" src="https://github.com/csoc-de/Shifts/assets/1177647/532b2a1b-0e89-428b-a1fe-96711589a1f7">

<img width="433" alt="Bildschirmfoto 2024-01-09 um 15 51 23" src="https://github.com/csoc-de/Shifts/assets/1177647/51ae9629-ebf0-4f78-ab07-3bb226b55622">

<img width="1169" alt="Bildschirmfoto 2024-01-09 um 15 51 48" src="https://github.com/csoc-de/Shifts/assets/1177647/ce2afb37-81e1-4794-b301-b97c99a989bc">

Ich habe erwartet, dass der Termin von Freitag 22:00 bis Samstag 01:30 Uhr erstellt wird.. wurde hier aber von Donnerstag zu Freitag erstellt.

**Comment by csoc-kevink** [comment]
Hi ikkez,

danke für den Pull-Request! :)
Da hat sich wohl ein kleiner Fehler in die Berechnung eingeschlichen...
Pull-Request ist angenommen und Fix ist ab Version 1.9.6 drin.
