### ISSUE TITLE
Settings work only with the initial group name

### ISSUE THREAD

**Issue by sistein** [csoc-de/Shifts#65]
Version: 1.9.5
Nextcloud: 28.0.1

Thank you very much for this app. 

While configuring in a test environment I realized that the configuration does not work for changed groupnames.

In my case I renamed a group"example" to "Example". Using Example in the config would not work - example works. 
I don't think that a code change is necessary but a hint in the readme (or on the config site itself) might help. 

 The original name of a group can be found while hovering over the group (showing the link http://nxc.example.de/index.php/settings/users/example-staff -> example-staff is correct).

**Comment by csoc-kevink** [comment]
Hi, thank you for the info.
Until now i didn't know that a rename of the group does not change the internal id.
I'll add this to the documentation.
