### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MKbyte** [csoc-de/Shifts#72]
Nextcloud 29.

When running make dev-setup i get the message: make: *** No rule to make target 'dev-setup'.  Stop.
I can change the settings but there is also no rules tab

**Comment by csoc-kevink** [comment]
Is there a "Makefile" in the directory where you try to start the command?

**Comment by MKbyte** [comment]
Yes there is

**Comment by MKbyte** [comment]
I managed to get make dev-setup working but get other messages:
added 6 packages, removed 48 packages, changed 16 packages, and audited 1467 packages in 9s

278 packages are looking for funding
  run `npm fund` for details

# npm audit report

postcss  <8.4.31
Severity: moderate
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
No fix available
node_modules/@vue/component-compiler-utils/node_modules/postcss
  @vue/component-compiler-utils  *
  Depends on vulnerable versions of postcss
  node_modules/@vue/component-compiler-utils
    vue-loader  15.0.0-beta.1 - 15.11.1
    Depends on vulnerable versions of @vue/component-compiler-utils
    node_modules/vue-loader
      @nextcloud/webpack-vue-config  *
      Depends on vulnerable versions of vue-loader
      node_modules/@nextcloud/webpack-vue-config

4 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
