### ISSUE TITLE
recreate shiftcalendar not possible

### ISSUE THREAD

**Issue by Jaaannis** [csoc-de/Shifts#73]
Hello,

i just deleted choosen shiftcalendar and recreate it by the same name.
After that calendar sync from shifts to calendar is not possible anymore (without any errors).

Is there a way to reset all (or this) settings for shift app ?

Thank you !

**Comment by csoc-kevink** [comment]
Hi,

the sync feature is a hacky mess and really error-prone. The most common error is that the id of the calendar is not exactly the same as in the config section.  
You can try to clean the corresponding tables in your database. There should be one for calendar-changes.

**Comment by Jaaannis** [comment]
okayy thank you for fast responce !
